Repository TeamBDMJ/zziririt-back, pull requests merged in 2024-04, with the labels that each got.

#130 ZRR-107 Bug: MailSender Bug Fix
  src/main/kotlin/kr/zziririt/zziririt/infra/mailsender/MailService.kt
Labels: 🐛bug

#137 ZRR-109 Fix: DB CQRS 도입 및 DB AWS RDS Aurora 이전
  src/main/kotlin/kr/zziririt/zziririt/api/HealthCheckController.kt
  src/main/kotlin/kr/zziririt/zziririt/global/AppStatusRunner.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/postgres/DataSourceConfiguration.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/postgres/RoutingDataSource.kt
  src/main/resources/application.yml
Labels: 📝 Fix

#143 ZRR-112 Fix: 로그 한글 인코딩 문제 해결을 위한 application.yml 수정
  src/main/resources/application.yml
Labels: 💚Chore

#145 ZRR-113 Feat: Popular Posts(TOP5)
  src/main/kotlin/kr/zziririt/zziririt/api/zzirit/controller/ZziritController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/zzirit/dto/response/ZziritCountResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/zzirit/service/ZziritService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/zzirit/repository/ZziritRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/zzirit/repository/ZziritRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/zzirit/ZziritQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/zzirit/ZziritQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/zzirit/dto/ZziritDto.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/redis/zzirit/ZziritRedisRepository.kt
Labels: ✨Feature

#150 ZRR-115 Refactor: cron 표현식 수정
  src/main/kotlin/kr/zziririt/zziririt/api/zzirit/service/ZziritService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/zzirit/ZziritQueryDslRepositoryImpl.kt
Labels: 🔨refactor

#153 ZRR-117 Release: Zziririt v1.1.1🎉
  build.gradle.kts
Labels: 💎Release

#155 ZRR-116 Docs: 최종발표 리드미 작성
  README.md
  img/architecture.png
  img/back.png
  img/collabTool.png
  img/front.png
  img/infra.png
  img/serviceScreen.png
  img/stack.png
  img/testCode.png
  img/timeLine.png
Labels: 📚documentation

#156 ZRR-118 Chore: RDS DB Scaled Down
  Dockerfile
Labels: 💚Chore
