Repository TeamBDMJ/zziririt-back, pull requests merged in 2024-03, with the labels that each got.

#8 ZRR-46 Add: 공통 예외 처리 핸들러 작성
  src/main/kotlin/kr/zziririt/zziririt/global/exception/CustomException.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/GlobalExceptionHandler.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/ModelNotFoundException.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/RestApiException.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/dto/ErrorResponse.kt
Labels: 📝add

#12 ZRR-4 Feat: 네이버 소셜 로그인 API 개발
  build.gradle.kts
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/SocialMemberRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/OAuthLoginController.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/SecurityConfig.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtDto.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtProvider.kt
  src/main/resources/application.yml
Labels: ✨Feature

#10 ZRR-47 Feat: s3 이미지 업로드 기능 구현
  build.gradle.kts
  src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/aws/S3Config.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/aws/S3Service.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/aws/UploadHelper.kt
  src/main/resources/application.yml
Labels: ✨Feature

#21 ZRR-50 Fix: Jwt 인증 불가한 현상 수정
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/SocialMemberRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/OAuthLoginController.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/SecurityConfig.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/UserPrincipal.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtDto.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtProvider.kt
  src/main/resources/application.yml
Labels: 🐛bug

#19 ZRR-55 Add: 공통 예외 처리 핸들러 수정 및 성공 응답시 반환 작성
  src/main/kotlin/kr/zziririt/zziririt/api/dto/CommonResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/global/ApiHelper.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/GlobalExceptionHandler.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/dto/ErrorResponse.kt
Labels: 📝add

#23 ZRR-32 Refactor: FAQ Create 코드리뷰의존결합 낮춤
  src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/CreateFaqRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/FaqResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/faq/model/FaqEntity.kt
Labels: 🔨refactor

#25 ZRR-21 Add: Application.yml 분리 및 Server 시작 상태 확인을 위한 AppRunner 작성
  src/main/kotlin/kr/zziririt/zziririt/global/AppStatusRunner.kt
  src/main/resources/application.yml
Labels: ✨Feature, 📝add

#26 ZRR-3 Feat: Post 기본 CRUD api 추가
  build.gradle.kts
  src/main/kotlin/kr/zziririt/zziririt/api/post/controller/PostController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/PostSearchCondition.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/SearchType.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/request/CreatePostRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/request/UpdatePostRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/response/PostResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/valid/SearchTypeValidation.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/model/PostEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/post/PostJpaRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/QueryDslSupport.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/dto/PostRowDto.kt
Labels: ✨Feature

#29 ZRR-52 Feat: FAQ Update 코드작성
  src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/UpdateFaqRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
Labels: ✨Feature

#35 ZRR-60 Feat: 회원 등급 조정 API 개발
  build.gradle.kts
  src/main/kotlin/kr/zziririt/zziririt/api/member/controller/.gitkeep
  src/main/kotlin/kr/zziririt/zziririt/api/member/controller/MemberController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/dto/.gitkeep
  src/main/kotlin/kr/zziririt/zziririt/api/member/dto/request/AdjustRoleRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/dto/request/SetBoardManagerRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/dto/response/GetMemberResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/service/.gitkeep
  src/main/kotlin/kr/zziririt/zziririt/api/member/service/MemberService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/MemberStatus.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/resources/application.yml
Labels: ✨Feature

#37 ZRR-43 Feat: 댓글 기본 CURD API 개발
  src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/comment/controller/CommentController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/comment/dto/CommentDto.kt
  src/main/kotlin/kr/zziririt/zziririt/api/comment/service/CommentService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/comment/model/CommentEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/comment/repository/CommentRepository.kt
Labels: ✨Feature

#28 ZRR-53 Test: Post Entity 단위 Test Code 작성 및 메서드 버그 수정
  src/main/kotlin/kr/zziririt/zziririt/domain/post/model/PostEntity.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/post/model/PostEntityTest.kt
Labels: ✅ Test

#39 ZRR-61 Bug: UserPrincipal 코드 수정으로 인한 Audit 버그 수정
  src/main/kotlin/kr/zziririt/zziririt/global/config/MemberAwareAudit.kt
Labels: 🐛bug

#41 ZRR-45 Bug: SocialMemberEntity Ban 관련 Property 추가에 따른 버그 발생
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/test/kotlin/kr/zziririt/zziririt/ZziriritApplicationTests.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/post/model/PostEntityTest.kt
Labels: 🐛bug

#36 ZRR-58 Chore: CI 환경 구성
  .github/workflows/backend-build-test.yml
Labels: 💚Chore

#43 ZRR-59 Feat: FAQ Delete API 개발
  src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
Labels: ✨Feature

#45 ZRR-62 Feat: FAQ 목록조회 API 개발.
  src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
Labels: ✨Feature

#46 ZRR-42 Feat: Report API 개발
  src/main/kotlin/kr/zziririt/zziririt/api/member/dto/request/AdjustRoleRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/report/controller/ReportController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/report/dto/request/BanMemberRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/report/dto/request/MemberReportRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/report/service/ReportService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/report/model/BannedHistoryEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/report/model/ReportEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/report/repository/BannedHistoryRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/report/repository/ReportRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/report/repository/ReportRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/report/ReportJpaRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/report/ReportQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/report/ReportQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/report/dto/ReportDto.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/comment/model/CommentEntityTest.kt
Labels: ✨Feature

#53 ZRR-67 Feat: 검색기능 캐싱(캐싱별 버저닝)
  build.gradle.kts
  src/main/kotlin/kr/zziririt/zziririt/api/post/controller/PostController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/PostSearchCondition.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/cache/CacheConfig.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/cache/CacheType.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/dto/PostRowDto.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/redis/RedisConfig.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/redis/post/PostSearchCacheRedisRepository.kt
  src/main/resources/application.yml
Labels: ✨Feature

#54 ZRR-69 Feat: Login History 개발
  src/main/kotlin/kr/zziririt/zziririt/api/member/dto/response/GetMemberResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/service/MemberService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/LoginHistoryEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/LoginHistoryRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/LoginHistoryRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/member/LoginHistoryJpaRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/OAuthLoginController.kt
Labels: ✨Feature

#56 ZRR-73 Chore: application.yml 및 env파일 변수명 변경 및build.gradle version 관리 변경
  build.gradle.kts
  src/main/kotlin/kr/zziririt/zziririt/global/AppStatusRunner.kt
  src/main/resources/application.yml
Labels: 💚Chore

#61 ZRR-75 Release: Zziririt 0.0.2 Version
  build.gradle.kts
Labels: 💎Release

#64 ZRR-75 Chore: add Dockerfile and update application.yml
  Dockerfile
  src/main/resources/application.yml
Labels: 💚Chore

#66 ZRR-77 Release: Zziririt v0.0.2
  build.gradle.kts
Labels: 💎Release

#69 ZRR-79 Refactor: OAuth2 소셜 로그인 기능 리팩토링
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/LoginHistoryRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/SocialMemberRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/SocialMemberRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/global/config/MemberAwareAudit.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/member/SocialMemberJpaRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/OAuthLoginController.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/dto/OAuth2MemberInfo.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/service/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/service/OAuth2MemberService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/service/SocialMemberService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/SecurityConfig.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtProvider.kt
Labels: 🔨refactor

#74 ZRR-80 Docs: README 작성
  README.md
  img/ZZIRIRIT_5.png
  img/architecture.png
  img/cicd.png
  img/doojooImage.png
  img/jiyoungImage.png
  img/misoImage.png
  img/moveukImage.png
  img/serviceScreen.png
  img/stack.png
  img/teamRule.png
  img/timeLine.png
Labels: 📚documentation

#77 ZRR-81 Docs: README 1.1 update
  README.md
  img/ciCd.png
  img/cicd.png
  img/teamCore.png
  img/teamCulture.png
  img/teamRule.png
  img/testCode.png
Labels: 📚documentation

#75 ZRR-71 Feat: Board 조회 api 및 정책 적용
  src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/FavoriteBoardDto.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/StreamerFormDto.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/SubscribeBoardDto.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/service/BoardService.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/controller/MemberController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/service/MemberService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/BoardActStatus.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/BoardEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/FavoriteBoardEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/StreamerFormEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/StreamerFormRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/board/BoardJpaRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/service/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/BoardQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/BoardQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/BoardRowDto.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/StreamerBoardRowDto.kt
Labels: ✨Feature

#83 ZRR-82 Feature: Icon, Icon Shop 개발
  src/main/kotlin/kr/zziririt/zziririt/api/icon/controller/IconController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/icon/dto/request/AddIconRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/icon/service/IconService.kt
  src/main/kotlin/kr/zziririt/zziririt/api/iconproduct/controller/IconProductController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/iconproduct/dto/IconSearchCondition.kt
  src/main/kotlin/kr/zziririt/zziririt/api/iconproduct/dto/request/BuyIconProductRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/iconproduct/dto/request/ChangeSaleStatusRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/iconproduct/dto/request/IconProductRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/iconproduct/dto/response/IconProductResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/iconproduct/dto/valid/IconSearchTypeValidation.kt
  src/main/kotlin/kr/zziririt/zziririt/api/iconproduct/service/IconProductService.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/controller/MemberController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/dto/request/SelectMyIconRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/member/service/MemberService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/icon/model/IconEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/icon/repository/IconRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/iconproduct/model/IconProductEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/iconproduct/model/SaleStatus.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/iconproduct/repository/IconProductRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/iconproduct/repository/IconProductRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/MemberIconEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/MemberIconRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/MemberIconRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/iconproduct/IconProductJpaRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/member/MemberIconJpaRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/service/OAuth2LoginSuccessHandler.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/iconproduct/IconProductQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/iconproduct/IconProductQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/iconproduct/dto/IconProductRowDto.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/member/MemberIconQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/member/MemberIconQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/member/SocialMemberQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/member/dto/GetMyIconsDto.kt
  src/test/kotlin/kr/zziririt/zziririt/api/member/service/MemberServiceTest.kt
Labels: ✨Feature

#87 ZRR-90 Refactor: Board 리팩토링
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/StreamerBoardRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/service/BoardService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/BoardEntity.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/board/model/BoardEntityTest.kt
Labels: 🔨refactor

#89 ZRR-89 Refactor: Post API 스펙 변경
  src/main/kotlin/kr/zziririt/zziririt/api/post/controller/PostController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/response/PostResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/global/config/MemberAwareAudit.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/dto/PostRowDto.kt
Labels: 🔨refactor, 📝add

#70 ZRR-72 Feat: FAQ-authorization-and-validation
  src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/CreateFaqRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/UpdateFaqRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
Labels: ✨Feature

#95 ZRR-93 Release: Zziririt v0.1.0🎉
  build.gradle.kts
Labels: 💎Release

#98 ZRR-94 Chore: 배포시 도커 컨테이너 타임존 Asia/Seoul로 설정하도록 backend-cd.yml 수정
  .github/workflows/backend-cd.yml
Labels: 💚Chore

#102 ZRR-97 Feat: Board Category 삭제 후 재개발
  src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/BoardCategoryResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/BoardRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/CategoryResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/CreateCategoryRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/UpdateCategoryNameRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/service/BoardService.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/service/CategoryService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/BoardCategoryEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/BoardEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/CategoryEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardCategoryRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/CategoryRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/BoardQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/BoardQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/BoardRowDto.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/ChildBoardRowDto.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/board/model/BoardEntityTest.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/comment/model/CommentEntityTest.kt
Labels: ✨Feature

#100 ZRR-99 Feat: JavaMailSender를 사용한 가입 안내 메일 발
  build.gradle.kts
  src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/mailsender/MailClient.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/mailsender/MailService.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/service/SocialMemberService.kt
  src/main/resources/application.yml
Labels: ✨Feature

#93 ZRR-92 Feat: FAQ-Entity,Service test-code 작성
  src/test/kotlin/kr/zziririt/zziririt/api/faq/service/FaqServiceTest.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/faq/model/FaqEntityTest.kt
Labels: ✨Feature

#104 ZRR-98: 게시판 구조 변경에 따른 Post API 수정 및 추가
  src/main/kotlin/kr/zziririt/zziririt/api/post/controller/PostController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/PostSearchCondition.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/request/CreatePostRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/request/UpdatePostRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/response/PostResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/model/PostEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/cache/CacheConfig.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/dto/PostRowDto.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/redis/post/PostSearchCacheRedisRepository.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/comment/model/CommentEntityTest.kt
  src/test/kotlin/kr/zziririt/zziririt/domain/post/model/PostEntityTest.kt
Labels: ✨Feature, 📝 Fix

#107 ZRR-100 Refactor: Board - Category 다대다 삭제
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/BoardCategoryResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/CreateCategoryRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/service/BoardService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/BoardCategoryEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/BoardEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/CategoryEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardCategoryRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/CategoryRepository.kt
Labels: 🔨refactor

#112 ZRR-96 Refactor: StreamerBoardApplication 이미지 업로드 수정, board url 조회 ap…
  src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/request/CreateCategoryRequest.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/response/BoardResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/response/BoardUrlSearchResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/dto/response/CategoryResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/service/BoardService.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/service/CategoryService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/BoardEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/model/CategoryEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/CategoryRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/board/BoardJpaRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/BoardQueryDslRepository.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/board/BoardQueryDslRepositoryImpl.kt
Labels: 🔨refactor

#115 ZRR-101 Feat: Point History
  src/main/kotlin/kr/zziririt/zziririt/api/member/service/MemberService.kt
  src/main/kotlin/kr/zziririt/zziririt/api/point/service/PointHistoryService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/member/model/ChangeDivision.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/point/model/PointHistoryEntity.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/point/repository/PointHistoryRepository.kt
  src/test/kotlin/kr/zziririt/zziririt/api/member/service/MemberServiceTest.kt
Labels: ✨Feature

#119 ZRR-103 Refactor: 게시판 아이디 활용 하위 카테고리 조회 api, 카테고리 테이블에 들어가던 null 수정,비…
  src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt
  src/main/kotlin/kr/zziririt/zziririt/api/board/service/BoardService.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt
Labels: 🔨refactor

#117 ZRR-102 Chore: Prometheus-Grafana Setting
  build.gradle.kts
  src/main/resources/application.yml
Labels: 💚Chore

#123 ZRR-105 Fix: Post And Comment API 버그 수정
  src/main/kotlin/kr/zziririt/zziririt/api/comment/dto/CommentResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/dto/response/PostResponse.kt
  src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt
  src/main/kotlin/kr/zziririt/zziririt/domain/comment/repository/CommentRepositoryImpl.kt
  src/main/kotlin/kr/zziririt/zziririt/infra/jpa/comment/CommentJpaRepository.kt
Labels: 🐛bug

#121 ZRR-104 Release: Zziririt v1.0.0🎉
  build.gradle.kts
Labels: 💎Release

#126 ZRR-106 Chore: application.yml update
  src/main/resources/application.yml
Labels: 💚Chore
